import React from 'react'
import './Homey.css'
import plant from './../../assets/plant.png'
import ShareLocalBody from './../../assets/ShareLocalBody.png'
import waste from './../../assets/waste.png'
import WasteHiWaste from './../../assets/WasteHiWaste.png'
import wastePlant from './../../assets/wastePlant.png'
import wasteRecycle from './../../assets/wasteRecycle.png'
const Homey = () => {
  return (
    <div className="body">
    <div className="central">
      <div className="marquee-wrapper" style={{ userSelect: 'none' }}>
        <div className="marquee-content scrollingX">
          {/* Clean Kerala Card */}
          <div className="card-testimonial">
            <article>
              <picture>
                <source media="(min-width: 768px)" srcSet={wasteRecycle} />
                <img src={wasteRecycle} alt="" />
              </picture>
              <h4 style={{ fontWeight: 900, textAlign: 'center' }}>
                CLEAN KERELA
              </h4>
              <article className="short-description">
                <p>
                  Clean Kerala Company having the share of Local Self Government
                  Institutions is transporting the waste to cement plant and -
                  14,235T of recyclables collected by HKS during 2021-22 and
                  given Rs. 6.11 Crore. 3 PET/PETE bottles of drinking water of
                  capacities less than 500 ml.
                </p>
              </article>
            </article>
          </div>

          {/* LSG Card */}
          <div className="card-testimonial">
            <article>
              <picture>
                <source
                    media="(min-width: 768px)"
                    srcSet={ShareLocalBody}
                />
                <img src={ShareLocalBody} alt="" />
              </picture>
              <h4 style={{ fontWeight: 900, textAlign: 'center' }}>LSG</h4>
              <article className="short-description">
                <p>
                  The Assessment reveals that more than 43% of the LSGIs do not
                  credit the amount generated by way of sales to the HKS
                  members’ account regularly.
                </p>
              </article>
            </article>
          </div>

          {/* Enhancing Young Minds Card */}
          <div className="card-testimonial">
            <article>
              <picture>
                <source media="(min-width: 768px)" srcSet={plant} />
                <img src={plant} alt="" />
              </picture>
              <h4 style={{ textAlign: 'center' }}>ENHANCING YOUNG MINDS</h4>
              <article className="short-description">
                <p>
                  Active participation of students to inculcate the spirit of
                  green India among the future of India.
                </p>
              </article>
            </article>
          </div>

          {/* Waste Generation (Road Construction) Card */}
          <div className="card-testimonial">
            <article>
              <picture>
                <source media="(min-width: 768px)" srcSet={waste} />
                <img src={waste} alt="" />
              </picture>
              <h4 style={{ textAlign: 'center' }}>WASTE GENERATION</h4>
              <article className="short-description">
                <p>
                  Kerala has so far used 2,800 tonnes of plastic waste in the
                  construction of 4,967.31 km of roads.
                </p>
              </article>
            </article>
          </div>

          {/* Waste Generation (Municipal Solid Waste) Card */}
          <div className="card-testimonial">
            <article>
              <picture>
                <source media="(min-width: 768px)" srcSet={WasteHiWaste} />
                <img src={WasteHiWaste} alt="" />
              </picture>
              <h4>WASTE GENERATION</h4>
              <article className="short-description">
                <p>
                  3453 metric ton municipal solid waste is generated in Kerala.
                </p>
              </article>
            </article>
          </div>

          {/* Non-Renewable Energy (Biogas Plant) Card */}
          <div className="card-testimonial">
            <article>
              <picture>
                <source media="(min-width: 768px)" srcSet={wastePlant} />
                <img src={wastePlant} alt="" />
              </picture>
              <h4>NON-RENEWABLE ENERGY</h4>
              <article className="short-description">
                <p>
                  The usage of non-renewable sources of energy like firewood
                  decreased by 15% after the construction of a biogas plant.
                </p>
              </article>
            </article>
          </div>
        </div>
      </div>
    </div>
    </div>
  )
}

export default Homey
